from services.email_service import (
    send_email
)

from services.file_memory import (
    get_last_file
)
import os

from dotenv import load_dotenv
load_dotenv()


def email_last_file(
    recipient=None
    
):
    if not recipient:

        recipient = os.getenv(
        "DEFAULT_EMAIL"
    )

    filepath = get_last_file()

    if not filepath:

        return "No file available."

    return send_email(
        recipient=recipient,
        subject="Jarvis Report",
        body="Generated by Jarvis",
        attachment=filepath
    )